import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Read .env.local manually (portable across all Node versions)
try {
  const env = readFileSync(resolve(__dirname, '../.env.local'), 'utf8');
  for (const line of env.split('\n')) {
    const eq = line.indexOf('=');
    if (eq > 0) process.env[line.slice(0, eq).trim()] = line.slice(eq + 1).trim();
  }
} catch { /* .env.local absent, rely on process.env */ }

const TOKEN = process.env.UEX_API_TOKEN;
if (!TOKEN) {
  console.error('UEX_API_TOKEN manquant. Créez .env.local avec :\nUEX_API_TOKEN=votre_token');
  process.exit(1);
}

const BASE = 'https://api.uexcorp.space/2.0';
const headers = { Authorization: `Bearer ${TOKEN}` };

async function fetchList(endpoint) {
  const res = await fetch(`${BASE}/${endpoint}/`, { headers });
  if (!res.ok) throw new Error(`${endpoint} → HTTP ${res.status}`);
  const json = await res.json();
  if (json.status !== 'ok') throw new Error(`${endpoint} → ${json.message}`);
  return Array.isArray(json.data) ? json.data : Object.values(json.data);
}

console.log('Fetching UEX data…');
const [commodities, terminals] = await Promise.all([
  fetchList('commodities'),
  fetchList('terminals'),
]);

// Log one sample per endpoint to verify field names
console.log('\nCommodity sample:', JSON.stringify(commodities[0], null, 2));
console.log('\nTerminal sample:', JSON.stringify(terminals[0], null, 2));

const commodityNames = [...new Set(
  commodities
    .filter(c => c.is_available === 1)
    .map(c => c.name)
    .filter(Boolean)
)].sort((a, b) => a.localeCompare(b));

const destinationNames = [...new Set(
  terminals
    .filter(t => t.type === 'commodity' && t.is_available === 1)
    .map(t => t.displayname)
    .filter(Boolean)
)].sort((a, b) => a.localeCompare(b));

const out = `// Generated by scripts/update-options.mjs — ne pas modifier manuellement.
// Mettre à jour : npm run update-options

export const DESTINATION_OPTIONS = [
${destinationNames.map(n => `  ${JSON.stringify(n)},`).join('\n')}
];

export const COMMODITY_OPTIONS = [
${commodityNames.map(n => `  ${JSON.stringify(n)},`).join('\n')}
];
`;

writeFileSync(resolve(__dirname, '../src/data/contractOptions.ts'), out);
console.log(`\n✓ ${destinationNames.length} destinations, ${commodityNames.length} commodités écrites dans src/data/contractOptions.ts`);
